# Generated by Django 3.1.4 on 2022-08-01 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_catimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimg',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product'),
        ),
    ]
